### ISSUE TITLE
Doesn't compile with GHC 9.0.1

### ISSUE THREAD

**Issue by expipiplus1** [mkloczko/derive-storable-plugin#5]
I guess some GHC internal things have moved around

```
Building library for derive-storable-plugin-0.2.3.3..
[1 of 8] Compiling Foreign.Storable.Generic.Plugin.Internal.Helpers ( src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs, dist/build/Foreign/Storable/Generic/Plugin/Internal/Helpers.o, dist/build/Foreign/Storable/Generic/Plugin/Internal/Helpers.dyn_o )

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:16:1: error:
    Could not find module ‘CoreSyn’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
16 | import CoreSyn (Bind(..),Expr(..), CoreExpr, CoreBind, CoreProgram, Alt)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:17:1: error:
    Could not find module ‘Literal’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
17 | import Literal (Literal(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:18:1: error:
    Could not find module ‘Id’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
18 | import Id  (isLocalId, isGlobalId,Id)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:19:1: error:
    Could not find module ‘Var’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
19 | import Var (Var(..))
   | ^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:21:1: error:
    Could not find module ‘Var’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
21 | import Var (TyVarBinder(..), VarBndr(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:25:1: error:
    Could not find module ‘Name’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
25 | import Name (getOccName,mkOccName)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:26:1: error:
    Could not find module ‘OccName’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
26 | import OccName (OccName(..), occNameString)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:27:1: error:
    Could not find module ‘Name’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
27 | import qualified Name as N (varName)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:28:1: error:
    Could not find module ‘SrcLoc’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
28 | import SrcLoc (noSrcSpan)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:29:1: error:
    Could not find module ‘Unique’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
29 | import Unique (getUnique)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:31:1: error:
    Could not find module ‘HscMain’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
31 | import HscMain (hscCompileCoreExpr)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:32:1: error:
    Could not find module ‘HscTypes’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
32 | import HscTypes (HscEnv,ModGuts(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:33:1: error:
    Could not find module ‘CoreMonad’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
33 | import CoreMonad (CoreM,CoreToDo(..), getHscEnv)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:34:1: error:
    Could not find module ‘BasicTypes’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
34 | import BasicTypes (CompilerPhase(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:36:1: error:
    Could not find module ‘Type’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
36 | import Type (isAlgType, splitTyConApp_maybe)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:37:1: error:
    Could not find module ‘TyCon’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
37 | import TyCon (algTyConRhs, visibleDataCons)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:39:1: error:
    Could not find module ‘TyCoRep’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
39 | import TyCoRep (Type(..), TyBinder(..), TyCoBinder(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:43:1: error:
    Could not find module ‘TysWiredIn’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
43 | import TysWiredIn (intDataCon)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:44:1: error:
    Could not find module ‘DataCon’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
44 | import DataCon    (dataConWorkId,dataConOrigArgTys)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:46:1: error:
    Could not find module ‘MkCore’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
46 | import MkCore (mkWildValBinder)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:48:1: error:
    Could not find module ‘Outputable’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
48 | import Outputable (cat, ppr, SDoc, showSDocUnsafe)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:49:1: error:
    Could not find module ‘CoreMonad’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
49 | import CoreMonad (putMsg, putMsgS)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:63:1: error:
    Could not find module ‘Var’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
63 | import Var
   | ^^^^^^^^^^
builder for '/nix/store/wys0wvq2kn3cvp8g32qpkbk1b5abfb3k-derive-storable-plugin-0.2.3.3.drv' failed with exit code 1
```

**Comment by mkloczko** [comment]
Will take a look into it in two weeks.

**Comment by expipiplus1** [comment]
Thanks :)

**Comment by mkloczko** [comment]
Done! Uploaded the new version to Hackage.

**Comment by expipiplus1** [comment]
Thanks!
